### ISSUE TITLE
Recreate  missing press release on new website

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [oasis-dev/oasis-new-website#133] opened 2021-05-17 15:01 UTC
https://www-legacy.oasis-open.org/news/pr/oslc-approves-five-open-source-specifications-for-integrating-software-lifecycle-tools

Didn't transfer over so need to recreate.

**Comment by chet-ensign** [comment] 2021-05-20 15:05
Duplicate of 132. Closing this one.

**Closed as completed by chet-ensign** 2021-05-20 15:05 UTC
Labels: duplicate
