### ISSUE TITLE
TC email archives are displaying incorrectly

### ISSUE THREAD

**Issue by schurbet** [oasis-dev/oasis-new-website#102] opened 2020-12-15 19:15 UTC

**Comment by chet-ensign** [comment] 2020-12-16 14:54
This is a duplicate of issue #30. Jessie is still working with Higher Logic to fix the problem.

**Comment by chet-ensign** [comment] 2021-05-20 15:06
Jesse and HM fixed the problem. Closing this ticket.

**Closed as completed by chet-ensign** 2021-05-20 15:06 UTC
Labels: bug, duplicate, In progress
