### ISSUE TITLE
Past Event Search

### ISSUE THREAD

**Issue by jane-harnad** [oasis-dev/oasis-new-website#108] opened 2021-01-11 18:00 UTC
Is it possible to adjust the way past events appear when selecting that search option? At the moment, it runs oldest to newest. Would prefer to see the most recent past events to appear at the top of the page. Please let me know.

https://www.oasis-open.org/events/

**Comment by chet-ensign** [comment] 2021-01-11 18:52
This is also raised in #53. I opened HumanMade issue https://github.com/humanmade/OASIS/issues/259 to capture this requirement.

**Comment by CarolGeyer** [comment] 2021-01-14 21:10
Duplicate of issue #53.

**Closed as completed by CarolGeyer** 2021-01-14 21:10 UTC
Labels: duplicate, enhancement, Content, HM
